version: '3.8'

services: 
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: laravel-api
    container_name: laravel-api
    restart: always
    environment:
      # Xdebug configurations
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001 remote_enable=1
    volumes:
      - ./api:/var/www/html:cached
    ports:
      - 8080:80

  db:
    image: postgres
    container_name: laravel-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: superusersecretpassword
      PSQL_DATABASE: laravel_db
      PSQL_USERNAME: api
      PSQL_PASSWORD: api   
    volumes:
      # [Do Not Change] binding volume for init.sql
      - ./.docker/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
      # binding volume for Postgres database
      - ./db:/var/lib/postgresql/data
    ports: 
      - 9090:5432